language: java
sudo: false
jdk:
    - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
notifications:
    email: false
cache:
    directories:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
